### PR TITLE
Added Instance Segmentation Support

### PR DESCRIPTION
**Pull request by Saurav-D**
# Peer Review Information

Added instance segmentation support in COCOInstancesTransformer which use RLE format for segmentation.

# Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by Robotatron** [comment]
Is it possible to already use this PR to convert from Unity JSON to COCO for instance segmentation?
Will `datasetinsights convert -i <input-directory> -o <output-directory> -f COCO-Instances` work with this PR for instance segmentation?

**Comment by Robotatron** [comment]
@Saurav-D You closed the PR. Does that mean this PR will not be merged?

**Comment by Saurav-D** [comment]
> @Saurav-D You closed the PR. Does that mean this PR will not be merged? The ability to convert Unity Perception data to COCO with instance segmentation is really needed.

@Robotatron We have removed all convertors from this repo and moved to `dataformatter` which will have all convertors. While the repository is not public it you can access it through [pypi](https://pypi.org/project/dataformatter/). We'll add the instance segmentation support there by the end of this week.

**Review by davidwang-unity — APPROVED** [review]
LGTM!

**Review by salehe-ee — APPROVED** [review]
Changes look good. Correctly handles images with transparency channel.

**Pull request merged**
